import { LoveLanguage } from './content';

// Concrete daily-doable actions per love language. Curated for low
// friction — anyone can attempt any of these without special setup
// or spending. Language keys match LoveLanguage from content.ts.
//
// Used by services/loveLanguageNudgeService.ts to pick 3 items each
// week deterministically (date + coupleId hash) so both partners see
// the same suggestions when they open the Sunday nudge.
//
// Pool size: 20 per language (100 total). Enough that the weekly
// deterministic pick won't feel repetitive for many months even
// though each week is a random-order shuffle of the same pool.

export const LOVE_LANGUAGE_ACTIONS: Record<LoveLanguage, string[]> = {
  words: [
    'Send them a text listing 3 things you love about them',
    'Leave a voice memo saying "I appreciate you because..."',
    'Tell them something specific they did this week that you noticed',
    'Compliment their appearance without them prompting',
    'Write a short "you make my day better when..." note and leave it where they will find it',
    'Thank them out loud for something small they usually do',
    'Say "I love you" without any lead-up',
    'Tell them one quality you admire in them',
    'Repeat back something they told you last week, show you were listening',
    'Text them mid-day: "Just thinking about you"',
    'Tell them one thing you noticed today that they did well',
    'Send a photo of something and say "reminded me of you"',
    'Post an appreciative note somewhere they will see it — fridge, lock screen, DM',
    'Give them credit out loud when they helped with something',
    'Compliment their laugh, their mind, something non-physical',
    'Repeat their favourite quote back to them, unprompted',
    'Text them a memory of the two of you that still makes you smile',
    'Tell them one hope you have for the two of you',
    'Say "thank you for being you" without needing a reason',
    'Introduce them proudly, not just by name',
  ],
  acts: [
    'Make their coffee or tea the way they like it before they ask',
    'Take one small task off their plate today without mentioning it',
    'Fill up their car with fuel',
    'Pack their lunch or breakfast',
    'Do the dishes even if it is their turn',
    'Handle a chore they have been putting off',
    'Pick up something they need on your way home',
    'Set out their clothes for tomorrow',
    'Make the bed together in the morning',
    'Bring them something they did not know they needed — water, snack, phone charger',
    'Fold their laundry and put it away',
    'Load the dishwasher without being asked',
    'Charge their phone when it is dying',
    'Grab their bag or coat when you are leaving together',
    'Refill their water while they are working',
    'Handle the trash tonight even if it is not your night',
    'Wipe down the counters after cooking',
    'Bring them a warm blanket when they look cold',
    'Answer a message they have been dreading, together',
    'Cancel one thing on their calendar they secretly wish they did not have to do',
  ],
  gifts: [
    'Bring home their favourite snack from the store',
    'Send them a link to something you know they would love, no reason',
    'Pick a flower on your walk and bring it home',
    'Buy the small thing they mentioned wanting weeks ago',
    'Save them the last piece of something you are both eating',
    'Leave a small treat on their pillow',
    'Send them a link to a show or book you think they would enjoy',
    'Bring them coffee from the good place, not the closest',
    'Wrap something small in fancy paper just because',
    'Save something they mentioned wanting, then surprise them with it later',
    'Save an article you read to send them later',
    'Buy them coffee on your morning run',
    'Bring home a leaf, shell, or stone you found on your walk',
    'Screenshot a meme that made you laugh, send it',
    'Add a treat to your grocery order that only they would notice',
    'Frame a small photo you both like',
    'Buy the fancy version of something they use daily',
    'Pick up their favourite takeout unprompted',
    'Leave a note in their book, jacket pocket, or lunchbox',
    'Order that thing they have been "going to buy for months"',
  ],
  time: [
    'Put your phone in another room for the next hour',
    'Ask about their day and actually listen without checking notifications',
    'Take a 20-minute walk together with no destination',
    'Cook a meal together, no TV in the background',
    'Watch the sunset together, no talking required',
    'Sit with them while they do something they love',
    'Plan a phone-free evening this week',
    'Have breakfast together without screens on',
    'Drive somewhere together with music instead of podcasts',
    'Lie in bed for 15 minutes after waking, no scrolling',
    'Turn off the TV and just talk for 15 minutes',
    'Sit outside with them, no phones, coffee or tea in hand',
    'Play a board game or card game together tonight',
    'Show up to something they care about — a workout, hobby, or event',
    'Ask them a "would you rather" question and actually discuss the answer',
    'Cook their favourite meal side by side',
    'Take a bath or shower together, no agenda',
    'Look through old photos together for 10 minutes',
    'Plan a small trip together — even just tomorrow\'s dinner counts',
    'Wake up 15 minutes early so you have time together before the day starts',
  ],
  touch: [
    'Hold their hand while walking somewhere',
    'Give them a 30-second hug, a real one, not a passing squeeze',
    'Rest your hand on their back while you are talking to them',
    'Give them a shoulder rub without them asking',
    'Kiss them on the forehead',
    'Sit close enough to touch — knees, thighs, arm to arm',
    'Play with their hair while watching TV',
    'Give them a foot rub tonight',
    'Cuddle for 10 minutes with no follow-up expectation',
    'Slow-dance in the kitchen to one song',
    'Kiss the back of their neck when you pass them in the kitchen',
    'Rest your head on their shoulder while sitting together',
    'Trace their arm or back lightly while you are talking',
    'Hug them from behind unexpectedly',
    'Interlock fingers when you are driving together',
    'Give a real welcome-home hug at the door, not a wave',
    'Sit on the same couch, close, not on opposite ends',
    'Squeeze their hand three times, silent "I love you"',
    'Give them a scalp rub for 60 seconds',
    'Lean into them during the boring parts of a movie',
  ],
};
